### ISSUE TITLE
DDOS & out of memory & disk full

### ISSUE THREAD

**Issue by krystianj-escola** [EscolaLMS/Images#9]
params width i height are no secure.

examples:
1) width or height: -10 => file null - no image || HTTP Status 500
2) width or height: 10000 => very disk usage
3) width or height: 1mln => out of memory

**Comment by qunabu** [comment]
My opinion on that 

1. Service provider should include publishable config https://laravel.com/docs/8.x/packages#configuration. 
That config should include `min (uint)`,`max (uint)`,`allowed_widths (array uints)', `allowed_heigths  (array uints)`  with default values 
```php
[
  'min' => 10, 
  'max' => 1000, 
  'allowed_widths' => null, 
  'allowed_heights' => null
]
```
or something like that 
2. there should be tests for each of given edge cases
3. API to this should use [rate-limiting](https://laravel.com/docs/8.x/rate-limiting) by default with low number 

@krystianj-escola @pa-cholek @MWL91 any thoughts ?

**Comment by pa-cholek** [comment]
We could also prevent upscaling pictures (limit max width/height to max width/height of original picture)

**Comment by MWL91** [comment]
It could work also as register of new sizes in config, by name. It that case frontend may ask for specific sług of size that is registered, and sizes will be hidden from public request, like it is done in Wordpress (in a good way).

**Comment by qunabu** [comment]
@krystianj-escola @MWL91 can you check now

**Comment by MWL91** [comment]
It looks ok, but when i look at: https://github.com/EscolaLMS/Images/commit/4cb3cf82bee36a3aafe835b60a137b4f3a436149 I can not see test for this issue (should be written to never have the issue again). 

Also there is a little bit wired, having `determineWidthAndHeight`, that check for slug, and for available sizes with undocumented array parameter. If I would like to change or use that private method, I will don't know what should be pass there without read the code. However it's not about solution, but about style, and architecture.

If we want to have it written in not open for modification style, like it is now, then I don't see useful to separate this method if it only check for slug size, and size, so its not SRP.

```php
list($width, $height) = $this->determineWidthAndHeight($img, $params);
```

I would recommend moving the logic of searching for the slug configurated inside render and if is not available, use logic from `determineWidthAndHeight` between 68 and 73 line.

It would be even better if it could use strategy, to be more editable and extendable, but I don't know if we don't have overengineering then, when its simply change image size.

However I think we must have test that cover this issue, and proof that it works. By reading current code I'm not sure 100%, but it only seems to be ok.

**Comment by MWL91** [comment]
PS. `RateLimiter` could be a middleware too, then we prevent controller to have logic, and on specific request developer could disable it when required or change rules.
